# Generated by Django 5.2.6 on 2025-10-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_customer_invoice_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billed_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
