# Generated by Django 5.2.6 on 2025-10-16 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_billed_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='tax',
            new_name='discount',
        ),
    ]
