# Generated by Django 4.2.7 on 2025-11-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='subdomain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
