# Generated by Django 4.2.7 on 2025-11-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_make_subdomain_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='db_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
