# Generated by Django 4.2.7 on 2025-11-28 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_client_db_name'),
    ]

    operations = [
    ]
