# Generated by Django 4.2.7 on 2025-11-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_make_db_user_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='db_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
