# Generated by Django 4.2.7 on 2025-11-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_make_db_host_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='db_port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
