# Generated by Django 4.2.7 on 2025-11-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0017_fix_all_tenant_fields_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='access_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='tenant_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _populate_codes(apps),
            reverse_code=migrations.RunPython.noop,
        ),
    ]


def _populate_codes(apps):
    Client = apps.get_model('tenants', 'Client')
    for client in Client.objects.all():
        if not client.tenant_code:
            client.tenant_code = client.schema_name
            client.save(update_fields=['tenant_code'])
