# Generated by Django 4.2.7 on 2025-11-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0018_client_access_pin_client_tenant_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to deactivate this tenant and prevent access'),
        ),
    ]
