# Generated by Django 5.2.6 on 2025-09-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('pharmacist', 'Pharmacist'), ('admin', 'Admin'), ('staff', 'Staff')], max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
