# Generated by Django 5.2.6 on 2025-11-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('pharmacist', 'Pharmacist'), ('admin', 'Admin')], max_length=50),
        ),
    ]
