<<<<<<< Updated upstream
# Generated by Django 5.2.6 on 2025-10-16 06:12

import django.db.models.deletion
=======
# Generated by Django 5.2.6 on 2025-10-16 16:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
>>>>>>> Stashed changes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< Updated upstream
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> Stashed changes
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.CharField(max_length=150)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
        ),
    ]
