# Generated by Django 5.2.6 on 2025-10-17 01:09

import django.db.models.deletion
import pytz.tzinfo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierinvoice',
            name='date',
            field=models.DateField(default=pytz.tzinfo.DstTzInfo.localize),
        ),
        migrations.CreateModel(
            name='SupplierInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('batch_number', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('mfg_date', models.DateField()),
                ('exp_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supplier.supplierinvoice')),
            ],
        ),
    ]
