# Generated by Django 5.2.6 on 2025-10-17 01:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_alter_supplierinvoice_date_supplierinvoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='received_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
