# Generated by Django 5.2.6 on 2025-10-16 16:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_medicine_batch_number'),
        ('supplier', '0002_supplierinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='SupplierInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supplier.supplierinvoice')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_invoice_items', to='medicine.medicine')),
            ],
        ),
    ]
