# Generated by Django 5.2.6 on 2025-10-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_supplierinvoice_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='pan_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
