# Generated by Django 5.2.6 on 2025-10-17 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(choices=[('tablet/capsule', 'Tablet/Capsule'), ('liquid', 'Liquid'), ('patch', 'Patch'), ('cream', 'Topical Cream')], default='tablet/capsule', max_length=20)),
                ('mfg_date', models.DateField()),
                ('exp_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_qty', models.PositiveIntegerField(default=0)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='supplier.supplier')),
            ],
        ),
    ]
