# Generated by Django 5.2.6 on 2025-11-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('tablet/capsule', 'Tablet/Capsule'), ('liquid', 'Liquid'), ('patch', 'Patch'), ('dose form', 'Dose Form'), ('ointment', 'Ointment'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('cream', 'Topical Cream')], default='tablet/capsule', max_length=20),
        ),
    ]
