# Generated by Django 5.0.6 on 2025-09-29 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='company',
            new_name='brand_name',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='description',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='id',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='stock',
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('tablet/capsule', 'Tablet/Capsule'), ('liquid', 'Liquid'), ('patch', 'Patch'), ('cream', 'Topical Cream')], default='tablet/capsule', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='stock_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='supplier.supplier'),
        ),
    ]
