# Generated by Django 5.2.6 on 2025-10-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_rename_company_medicine_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
