# Generated by Django 5.2.6 on 2025-10-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_alter_medicine_medicine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
